name: Terraform Pipeline
on: [push]
jobs:
   Terraform-deploy:
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
        id-token: write
      steps:
        - name: git clone of my repo
          uses: actions/checkout@v3
        
        - name: AWS authentication
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: arn:aws:iam::177225465752:role/github-oidc
            aws-region: us-east-1
            role-session-name: GithubDeployment

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format
          id: fmt
          run: terraform fmt -check
